### ISSUE TITLE
Nether terrain generation crash

### ISSUE THREAD

**Issue by Tommeh1** [AllTheMods/Gravitas2#101]
No crash report was generated, but i was able to extract the following from the debug log:
Initially TerraFirmaCraft spammed this a few dozen times:
```java
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]: Error in 'MoreJSEvents.structureAfterPlace': Tried to access ChunkDataProvider but none was present on net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@7d83f9a3
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]: java.lang.IllegalStateException: Tried to access ChunkDataProvider but none was present on net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@7d83f9a3
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.dries007.tfc.world.chunkdata.ChunkDataProvider.get(ChunkDataProvider.java:43)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.dries007.tfc.world.feature.ErosionFeature.m_142674_(ErosionFeature.java:47)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at java.lang.reflect.Method.invoke(Method.java:578)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.MemberBox.invoke(MemberBox.java:160)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Interpreter.interpret(Interpreter.java:370)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Context.callSync(Context.java:1290)
[07Jan2024 04:32:36.964] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Interpreter.interpret(Interpreter.java:370)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Context.callSync(Context.java:1290)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Context.doTopCall(Context.java:1307)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Context.callSync(Context.java:1290)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.Context.callSync(Context.java:1290)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy76.onEvent(Unknown Source)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …kubejs.event.EventHandler.postToHandlers(EventHandler.java:304)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …kubejs.event.EventHandler.post(EventHandler.java:272)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …kubejs.event.EventHandler.post(EventHandler.java:226)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at …kubejs.event.EventHandler.post(EventHandler.java:179)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.levelgen.structure.StructureStart.handler$zbi000$morejs$invokeEventAfterPlace(StructureStart.java:539)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.levelgen.structure.StructureStart.m_226850_(StructureStart.java:94)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.chunk.ChunkGenerator.m_223080_(ChunkGenerator.java:320)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:319)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
[07Jan2024 04:32:36.965] [Worker-Main702/ERROR] [KubeJS Server/]:   at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
```
Followed by this being spammed until the server locked up:
```java
[07Jan2024 04:32:37.035] [Server thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Chunk source main thread executor for minecraft:the_nether
net.minecraft.ReportedException: Feature placement
	at net.minecraft.server.level.ChunkMap.m_214912_(ChunkMap.java:658) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:541) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:549) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "idata" because "frame" is null
	at dev.latvian.mods.rhino.Interpreter.getSourcePositionFromStack(Interpreter.java:2244) ~[rhino-forge-2001.2.2-build.18.jar%23315!/:2001.2.2-build.18]
	at dev.latvian.mods.rhino.Context.getSourcePositionFromStack(Context.java:283) ~[rhino-forge-2001.2.2-build.18.jar%23315!/:2001.2.2-build.18]
	at dev.latvian.mods.kubejs.util.ConsoleJS.line(ConsoleJS.java:199) ~[kubejs-forge-2001.6.4-build.114.jar%23293!/:2001.6.4-build.114]
	at dev.latvian.mods.kubejs.util.ConsoleJS.log(ConsoleJS.java:208) ~[kubejs-forge-2001.6.4-build.114.jar%23293!/:2001.6.4-build.114]
	at dev.latvian.mods.kubejs.util.ConsoleJS.error(ConsoleJS.java:326) ~[kubejs-forge-2001.6.4-build.114.jar%23293!/:2001.6.4-build.114]
	at dev.latvian.mods.kubejs.util.ConsoleJS.error(ConsoleJS.java:335) ~[kubejs-forge-2001.6.4-build.114.jar%23293!/:2001.6.4-build.114]
	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:284) ~[kubejs-forge-2001.6.4-build.114.jar%23293!/:2001.6.4-build.114]
	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:226) ~[kubejs-forge-2001.6.4-build.114.jar%23293!/:2001.6.4-build.114]
	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:179) ~[kubejs-forge-2001.6.4-build.114.jar%23293!/:2001.6.4-build.114]
	at net.minecraft.world.level.levelgen.structure.StructureStart.handler$zbi000$morejs$invokeEventAfterPlace(StructureStart.java:539) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_226850_(StructureStart.java:94) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223080_(ChunkGenerator.java:320) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%2374!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:319) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2377!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23351!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
```

**Comment by Pumpkin7266** [comment]
can be closed since now nether gen is beneath
