### ISSUE TITLE
Game crash when player joins

### ISSUE THREAD

**Issue by GoldenMine0502** [AllTheMods/Gravitas2#157]
[16:36:12] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.lang.ClassCastException: class net.dries007.tfc.common.recipes.DamageInputsCraftingRecipe$Shapeless cannot be cast to class com.simibubi.create.content.processing.basin.BasinRecipe (net.dries007.tfc.common.recipes.DamageInputsCraftingRecipe$Shapeless is in module tfc@3.1.6 of loader 'TRANSFORMER' @7e31062c; com.simibubi.create.content.processing.basin.BasinRecipe is in module create@0.5.1.f of loader 'TRANSFORMER' @7e31062c)
        at com.simibubi.create.content.processing.basin.BasinOperatingBlockEntity.mddd081b$lambda$getMatchingRecipes$0$0(BasinOperatingBlockEntity.java:538) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:APP:woodencog.mixins.json:MixinBasinRecipe,pl:mixin:A}
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?] {}
        at java.util.TimSort.sort(TimSort.java:220) ~[?:?] {}
        at java.util.Arrays.sort(Arrays.java:1307) ~[?:?] {re:mixin}
        at java.util.ArrayList.sort(ArrayList.java:1721) ~[?:?] {re:mixin}
        at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392) ~[?:?] {}
        at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
        at com.simibubi.create.content.processing.basin.BasinOperatingBlockEntity.getMatchingRecipes(BasinOperatingBlockEntity.java:541) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:APP:woodencog.mixins.json:MixinBasinRecipe,pl:mixin:A}
        at com.simibubi.create.content.kinetics.mixer.MechanicalMixerBlockEntity.getMatchingRecipes(MechanicalMixerBlockEntity.java:219) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:classloading,pl:runtimedistcleaner:A}
        at com.simibubi.create.content.processing.basin.BasinOperatingBlockEntity.updateBasin(BasinOperatingBlockEntity.java:73) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:APP:woodencog.mixins.json:MixinBasinRecipe,pl:mixin:A}
        at com.simibubi.create.foundation.blockEntity.behaviour.simple.DeferralBehaviour.tick(DeferralBehaviour.java:41) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:classloading}
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?] {}
        at com.simibubi.create.foundation.blockEntity.SmartBlockEntity.forEachBehaviour(SmartBlockEntity.java:179) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:classloading,re:mixin}
        at com.simibubi.create.foundation.blockEntity.SmartBlockEntity.tick(SmartBlockEntity.java:82) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:classloading,re:mixin}
        at com.simibubi.create.content.kinetics.base.KineticBlockEntity.tick(KineticBlockEntity.java:97) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at com.simibubi.create.content.processing.basin.BasinOperatingBlockEntity.tick(BasinOperatingBlockEntity.java:56) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:APP:woodencog.mixins.json:MixinBasinRecipe,pl:mixin:A}
        at com.simibubi.create.content.kinetics.mixer.MechanicalMixerBlockEntity.tick(MechanicalMixerBlockEntity.java:125) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:classloading,pl:runtimedistcleaner:A}
        at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.m_155252_(SmartBlockEntityTicker.java:15) ~[create-1.20.1-0.5.1.f.jar%23263!/:0.5.1.f] {re:classloading}
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.level.Level.redirect$bdn000$observable$redirectTick(Level.java:3040) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:tfc.mixins.json:LevelMixin,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
        at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:tfc.mixins.json:LevelMixin,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:tfc.mixins.json:ServerLevelMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:A}
        ... 5 more

[crash-2024-02-11_16.37.15-server.txt](https://github.com/AllTheMods/Gravitas2/files/14233166/crash-2024-02-11_16.37.15-server.txt)

**Comment by GoldenMine0502** [comment]
i built a factory from a recipe that converts cobble into brick with chisel in basin
this causes that maybe
idk

**Comment by GoldenMine0502** [comment]
steel chisel does not cause (maybe when it is broken), not wrought iron chisel (normally worked)

**Comment by GoldenMine0502** [comment]
woodencog mod is problem. 
when i remove it i can join the world
