### ISSUE TITLE
server crashes when building gadgets gropes fluid blocks

### ISSUE THREAD

**Issue by Yoghurt4C** [AllTheMods/Gravitas2#217]
this permanently corrupts the chunk btw
```py
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property InverseBooleanProperty{name=natural, clazz=class java.lang.Boolean, values=[false, true]} as it does not exist in net.minecraft.world.level.material.EmptyFluid@71ed3bc8
        at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferriteco$
        at net.minecraft.world.level.block.LiquidBlock.handler$zbf000$inject$updateShape(LiquidBlock.java:600) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:class$
        at net.minecraft.world.level.block.LiquidBlock.m_7417_(LiquidBlock.java:121) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransform$
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60728_(MixinBlockStateBase.java:794) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransform$
        at net.minecraft.world.level.block.Block.m_49931_(Block.java:145) ~[server-1.20.1-20230612.114412-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:$
        at com.direwolf20.buildinggadgets2.common.blockentities.RenderBlockBE.setRealBlock(RenderBlockBE.java:176) ~[buildinggadgets2-1.0.7.jar%23272!/:1.0.7] {re:classloading}
        at com.direwolf20.buildinggadgets2.common.blockentities.RenderBlockBE.tickServer(RenderBlockBE.java:151) ~[buildinggadgets2-1.0.7.jar%23272!/:1.0.7] {re:classloading}
        at com.direwolf20.buildinggadgets2.common.blocks.RenderBlock.lambda$getTicker$1(RenderBlock.java:37) ~[buildinggadgets2-1.0.7.jar%23272!/:1.0.7] {re:classloading}
```
![image](https://github.com/AllTheMods/Gravitas2/assets/11313954/d69609a8-c33a-499c-aea0-b618195d0275)

go bother dire now I'm sure he'll care

**Comment by pietro-lopes** [comment]
This is caused because TFC Thermal Deposits add more states to fluids.
Dire and Lux needs to come into a common deal of what needs to be done to prevent this.
